### ISSUE TITLE
~/.CutiePie/path.config considered harmful.

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/SpecTcl#10]
When CutiePie starts for the very first time (standalone mode?) it writes a file, if that file does not yet exist

~/.CutiePie/path.config

That contains two paths:
1. The path to user scripts - not terrible.
2. The path to CutiePie's @prefix@ - terrible  see below.

The problem with this is that if I then run CutiePie in a different version of SpecTcl, the path to the CutiePie prefix is now wrong.   One clear problem (there may be others depending on how this  path is used (e.g. to establish search paths for CutiePie's modules)  is that a message CutiePie can output:

```
/usr/opt/spectcl/5.13-003/bin/CutiePie
/user/fox/.CutiePie exists!
/user/fox/.CutiePie/path.config exists
        #################################
        # Usage for CutiePie standalone #:
        #################################
         Please set the following env variables
         export INSTDIR=/usr/opt/spectcl/5.10-000
         and
         export USERDIR=/user/mrbanana/home/algo
```

Will have the wrong directory for INSTDIR as it comes from that path.config file which is wrong.
Question worth asking - why is it necessary to have that in a config file when it can be gotten in one of two ways:

1. The location of cutiepie itself (assuming arg0 is available it's just up one dir from that).
2.  The value of the @prefix@ makefile variable set at config time:  This is where the value for .path.config is put.

**Comment by giraudsimon** [comment]
Consider fixed in commits 2df4311 and c45f270.
