### ISSUE TITLE
V785N unpacker

### ISSUE THREAD

**Issue by cerizza** [FRIBDAQ/SpecTcl#115]
There may be an issue with the CAEN V785N adc unpacker. SpecTcl doesn't handle correctly the firing channel.
Possible cause could be this:
![image](https://github.com/FRIBDAQ/SpecTcl/assets/111457622/3ad4dd50-7176-4dd7-a7d2-91b697c60563)

**Comment by rfoxkendo** [comment]
This is sort of documented somewhen.  It's really the way the ADC is built.  The 785 has 2 ADC chips one for the even channels and one for the odd ones. The 785N just has one ADC chip stuffed - the even channeled one.

Those who have used this module come to know and accept this. Of course could do a separate v785N module type (alias in VMUSBReadout and new unpacker in VMUSBSpecTcl that is aware of this.

What you will see is that the even channels unpack e.g. set the parameter map to [list chan0 "" chan1 ""  chan2 ....]

**Comment by rfoxkendo** [comment]
NSCLDAQ-12.1-003 (under dev). now supports an -inputs option for the CV785 class.  This has valid values  ```ribbon``` and ```nim``` which SpecTcl can use to differentiate the two module types.  Since there also exists V785N e.g. this will work for those as well as those modules use the same readout driver in VMUSBReadout.

**Comment by rfoxkendo** [comment]
I propose a pure Tcl approach:  If the v785 configuration has an ```-inputs``` and the value  is ```nim``` then I can take the inputs map and spread it out e.g. if the inputs name mape is '''[list a b c d e f g]'''  and -inputs nim is present I can re-write that as 
```[list a "" b "" c "" d "" e "" f "" g]```

in the channel map and this will decode properly.

**Comment by rfoxkendo** [comment]
The commits above represent a tested resolution for this issue.  Pulling into 7.0-dev
