### ISSUE TITLE
Adding spectrum before data is gotten crashes CutiePie

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/SpecTcl#25]
1.  Start CutiePie.
2.  Click the "Add" button before getting any data.
3.  Dismiss the dialog that says that you need to get the data first:
CutiePie crashes with:

Traceback (most recent call last):
  File "/usr/opt/spectcl/5.13-006/Script/GUI.py", line 2158, in addPlot
    self.currentPlot.h_dict_geo[self.currentPlot.index] = (self.currentPlot.h_dict[self.currentPlot.index])["name"]
TypeError: 'NoneType' object is not subscriptable
Aborted

**Comment by giraudsimon** [comment]
Consider this issue fixed.
