### ISSUE TITLE
Cutie Pie - does not handle spectra that are not bound gracefully(?)

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/SpecTcl#27]
If a spectrum is defined but not bound to the shared memory.  CutiePie's Get Data button pops up a dialog stating that 

"The rest interface for SpecTcl is not started or hostname/port/mirror are not configured"

It is not an error in SpecTcl or Rustogramer to have spectra that are not in shared memory.

See Issue #19 for an example where this is useful.

**Comment by giraudsimon** [comment]
Similar to #28 I consider this issue fixed.
