### ISSUE TITLE
CutiePie assumes that /spectcl/spectrum/list is in the same order as bindings.

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/SpecTcl#28]
Along with the CutiePie assumption that all spectra are bound came another assumption that made it fail with first attempts at getting  rustogramer to work with it.
Specifically, the data frame that describes the spectra known to Cutie pie is gotten partly from the shared memory - where spectrum names are in the order of binding index and spectrum metadata are gotten from /spectcl/spectrum/list

These are, in general, not in the same order.  In SpecTcl an sbind -all _happens_ to allocate share memory header slots in alphabetical order because it binds by iterates over the map<std::string, CSpectrum*> which keeps track of all spectra and map iteration returns things in key order.

Rustogramer works differently and, in general, the spectcl/spectrum/list data will _not_ be in binding order.

Furthermore as indicated in Issue #27 even in SpecTcl there's not assurance all spectra are bound.

There are inefficient an efficient ways to deal with this:

*   Inefficient if for e.g. Gamma group number of spectra:  Foreach bound spectrum use /spectcl/spectrum/list?filter=the-name-of-the-bound-spectrum to get the metadata of _only_ that spectrum  but repeating for up to MAXSPEC could be time consuming - especially for a remote SpecTcl/Rustogramer.
* Efficient:  use spectcl/spectrum/list  with no filter then match up by name the ones returned with the bound spectra (this might also help with issue #27.)

**Comment by giraudsimon** [comment]
I think I can close #27 and #28 issues.
