### ISSUE TITLE
Cutie Pie - filling larger grids of Spectra is a lot of clicking/moving.

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/SpecTcl#29]
If I fill in a large grid of spectra using CutiePie I have to

1.  Click on the item to fill.
2. Select a spectrum from the drop down (2 clicks).
3. rinse and repeat.

This is actually why in Xamine

1. The spectrum chooser is a dialog list box since then you just need to double click on the item rather than click-move to the item click
2. There's an advance that automatically selects the 'next' frame to fill in 

In that scheme you can just keep selecting spectra and the chances for errors are decreased.
There should at least be an auto-selection of the 'next' frame.   Now in Xamine you can select what that means by setting the 'advance' but I don't think anybody ever selected anything other than one which steps across the columns and then returns to the first frame on the next row.

**Comment by cerizza** [comment]
Add the red rectangle to the next frame when adding new spectra withouth selecting the frame

**Comment by giraudsimon** [comment]
Merge pull request #32 intended to solve this.
