### ISSUE TITLE
draw "and" gates

### ISSUE THREAD

**Issue by giraudsimon** [FRIBDAQ/SpecTcl#9]
Would be good to be able to visualize somehow the intersection of a combination of gates. 
ex: if an "and" gate which is a combination of a slice and a contour is applied to a 1D spectrum, how to represent this "and" gate?

**Comment by rfoxkendo** [comment]
I don't see in general how you can do this.
Specifically 

*  The component gates may be (probably are) not drawable on the spectrum they're applied to (e.g. a particle ID gate to gate an energy-sum  spectrum where the particle ID either comes from a contour in e.g. E vs TOF or some computed parameter, and the Energy Sum is some computed parameter etc. with no obvious, computable relationship to the gate parameter).
*  The component gates themselves can be compound gates. for Example  suppose I have slices s1, s2, s3, s4:  I can define
    gate or_gate + {s1 s2};    # True if either s1 or s2 is true.
    gate another_or + {s3 s4}
    gate not - another_or
    gate and * {or_gate not}
    
    The point being that compound gates (-, + *) can have arbitrarily deep nesting.  They are evaluated by asking each dependent gate to evaluate itself and then applying the logical function to those evaluations (note that OR and And gates do short circuit evaluation in that an AND gate will be false once any of the dependent gates evaluates false and an OR gate will be true once any dependent gate evaluates to true.

Even in the simple case it's hard for me to see how to describe this visually.  In Xamine what was asked for, and eventually delivered, was a line of text that describes the spectrum - including the name of any gate that's applied to the spectrum.
